title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
nav_enabled: true
enable_copy_code_button: true

url: https://supraset.github.io

callouts:
  warning:
    title: Warning
    color: yellow-300

  caution:
    title: Caution
    color: red

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template